language: python

python:
  - "2.7"

install:
  - pip -v install -r requirements-dev.txt
  - pip -v install -r requirements.txt
  - pip -v install . --upgrade

script:
  - pytest

cache:
  - pip
  - directories:
    - $HOME/virtualenv
    - $HOME/.cache/pip
