language: python

python:
  - "2.7"

install:
  - pip -v install -r requirements-dev.txt
  - pip -v install -r requirements.txt
  - pip -v install .

script:
  - pytest

after_success:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.6.15/terraform_0.6.15_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - ./aws/deploy.sh

branches:
  only:
    - master
    - next

cache:
  - pip
  - directories:
    - $HOME/virtualenv
    - $HOME/.cache/pip
