language: python
python:
- '2.7'
before_install:
- ./travis/install-terraform.sh
- pip install awscli
- export PATH=$PATH:$HOME/terraform
install:
- pip -v install -r requirements-dev.txt
- pip -v install -r requirements.txt
- pip -v install .
script:
- ./travis/build.sh
branches:
  only:
  - master
  - next
  - prod
cache:
- pip
- directories:
  - $HOME/virtualenv
  - $HOME/.cache/pip
  - $HOME/terraform
env:
  global:
  - TRAVIS_AWS_ACCESS_KEY_ID: AKIAJBSOFDJSDGWCKQ3Q
  # TRAVIS_AWS_SECRET_KEY_ID
  - secure: Dppd5gVPbhjQVPUpYch/gIh+os3D/rDjLgoNyQNuURqsKQK92/LovbSKo7RqU2vz86Q1F4cNt1Bl+IWix3fPBXC1czd8P/fjIcr8rLu53YYFZ50Wh5/LD/D1bgYZurV032gOKL/CAK+iShes1In6qPU3tCcL5Zc0x0my9iMw4ptTg3qjTR576x4uapgZdMYL1UomGNEjTh2KBr1hIL5or/2uckV+kEkc3QHasPJL0h4RFUKtAgC2NDdq90TpQDujrm2zkYPK77BR56Ywvo8NgcaLWbM04OOMG+Eea9baCoERWdNG2dRQGpsi9x+daGCjBZb6+9RKaDw4NqJAa2NaMq3SPwa/uvqX4HhysXtWCHUIIlLfBUJ8lEUo11aoTL2kVBHBKcFvSIqZmRKrVTnu095MqUfEPUPSzip3ZyQ0/gR1Nz3SDwrSWLqpcp2eend1lZTpfFMixidaUhZtmJPFrJDldybI5wX711TGBeLmhX9s1p9EBmgi3G/Tzd7qJrHZQL2TIOe4e505OD/VHZMjeCbwEhN3i8PScZX+9TipJdk8276fYktrxdACeMpb6eAdMndcxTY+aogWdKhhAv8DRf9ltTvPVq7UsSprT1VbSrnZ8xONnxXXvCEk/diyxwA7tSn2rYrZr7bFqXQCLhmY0C/L70I0yCqTpelDtALORYo=
  - TRAVIS_AWS_ACCESS_KEY_ID_PROD: AKIAIJFNJEMML3AZFO7A
  # TRAVIS_AWS_SECRET_KEY_ID_PROD
  - secure: uduwWmSsKhJgtbGEqjsvKMsnHamRAKH/rUaopnczeGfT+vA9YwPJw3aUxpyH7Ez4aDPq50qmRyH+ovqBybW/3/MoHMZTLy8xqqSEaeDwZ+zzqQaPW/s6K9Wk9LWSlH+vCjuJHQpFQZrzw22ZqHJZ6CaWmaUxyypGBxi8cUVPvd+Sz3wZ28BZcsp/sFlN6wuz4U5q3PNB8KUmgJ6Maj9JHnrfcYXPoScsrUBv5eEHpJDhyiM4/PKIMRUFi6B5zfs2X+6981yfE5vfU/iIL4W9UGXpgjt6uiW20/JOH0jK0/wp6Oe13Gvsv1btiuw0QwRRIfE3SEoiaitZ3DFtOOW/SADNUDmNV++urIGoCXSv+0SIIjtbAbdzmESewLqxuvinpHZdV0dsoUfR5mX7au40ihZCsLzzd1/hgoKf1fB+NNpqAv0eSMbSFq2R3xBzBJNfRKADlJIdjU0Uf9VsKcg1PUeiQFGY1nInCTX26KKYDfSlfUHyaiAIkGPuV2PkoTRnsxjd0wBEK3cZaK9EBw/yBkt76newB8//Zc7wVudhi/kJlSLnnRyx6rbR3XRpQMCraP+zHSJzDo6qiNNNqo0IWCEEmEzoWYkEQWXAi4OWucyWy0vsT+/wR7O5F8IiSAEKjvL02zbI3ltwiTJtg0ZOYhBtsmCCtSMmwp3alhCcEao=
