language: python
python:
- '2.7'
before_install:
- ./travis/install-terraform.sh
- pip install awscli
- export PATH=$PATH:$HOME/terraform
install:
- pip -v install -r requirements-dev.txt
- pip -v install -r requirements.txt
- pip -v install .
script:
- ./travis/build.sh
branches:
  only:
  - geodesyml-0.4
  - master
  - test
  - prod
cache:
- pip
- directories:
  - $HOME/virtualenv
  - $HOME/.cache/pip
  - $HOME/terraform
env:
  global:
  - AWS_ACCESS_KEY_ID: AKIA2AV2YTL6SUSQP56W
  # AWS_SECRET_ACCESS_KEY, /geodesy-operations/iam-user/travis-ci/access-key/AKIA2AV2YTL6SUSQP56W/secret-access-key
  - secure: rK8M1gmoFIMs+iwOXJllrFGu7hLL8dcYoW1nSFEJ9/sZKA8uPL2O0OiSp8RSIV39a08/4SEdba1PhbCiYD7gxDXMg4i6y1l6cwyr1KGnaLEd6CnpZjul63lrIS4HvDxGUFFbu25wjT3p+g6RpLtFeTsQ82AXRT8U5Lx1sqEDfDQUy/mZ7JFts5U8c9brnG8pmTCGip61L1C2uXstIkMFmforEgr7MlMiCRpvLeMvq8tVUiNcqVgpkWY6yXqABhsWoB3bo10hL1vZ2mEoY8q4AIFmLVO0OpdZa4GaiEI4qYLfwEZLHLZeO0EEbTm+arxTEA21RoTWajEkBzItkLvvdgJMYQQJ8vWN5veC0/dr9apCuYUR/1Zzh+lBgOyMtFyL2GGdeC86J0ihw6eFB07QXphjNKyTAb2jqumssjEj4C1d+0JbIlSK4xLkUVih6svbNv0zNOUp4be9InIFUJg0HO3faCkbSVasHm2V17N/ldO/pOL0weYy+VSxbJ+mXVkPMaZI6waMVJfJ7kH0I0QxTdm9zkh3yQydThnDUY6uC9G40kY0avq0ZU14ASlSlNCibRI6HvmBdQWpO9dlYhGi/j4jZfmsj1VxMNE0yFDHFBtbaZrDaShzET0GawTAk4oB7+2/Lx8+JaEv9R/1bioRDRaAkwpo1zuQTSwYAU55IPU=
  - AWS_ACCESS_KEY_ID_PROD: AKIAZCGYKSL2ASSA5W7A
  # AWS_SECRET_ACCESS_KEY_PROD, /geodesy-operations-prod/iam-user/travis-ci/access-key/AKIAZCGYKSL2ASSA5W7A/secret-access-key
  - secure: PRN/2/7WUGkOGO6kzAEIR6Oz6mUYBtSL5sgqy9mozyI73jvE91QLnWsfG2vuJvK6ULg1WLhO6Nwh5lqw/vU6P2aKLm7pTm3RvwEFJ27Wdb3X18jwE5t3fPiLUkokQbIuwV5HkXss/9a6KOlrCoLDZqcH0ZKv5T7E7T76yiK2DW/uz3ExIqeiHsNLwkASPJUxKyTsCv94jiAOFiOrycf4l4ISrUm9OcdMO5TseBPbIrVXtkeoFE30oJsGh07xloCH7VU3NBWHmnDMy2NBLFJcZn9K1aaQxCIsRlxQWQNccjTXHz60CLSmMgnoO6iz/sp3zqGXfgmUn3EBjgKhotyotBY4seysrHgSTZ+BfT5ZMoCYJLzXRg7BNI4nM8o2ScRl0TgKEoI9SDLbnX9df4zzYteePh8EQlJAzI8tmpb3pGZDn0+zBjaY0aUDZH++ueh2NypmlUThTu9DT2F30xqoxzX35/uPeJxR/eMu6w2fhOPRClC33s409qECIqc/ZhrdUITbew8MCIHJtWvS/DJBOMh8MrhGBmn27cWXEv1LQIIs/yavLeC+Pk80au18wrMjBNb1FHqRYZxzlWc7Db+Huidq3fRd0jzb6ZfDh8UaV6Yc2JyeVTNIJKUt3I/5FRfElv17mJraZ/lDKmP5X4mR86ScjAoRNxoBw6rWuDnF07Q=
