environment="dev"
sns_arn="arn:aws:sns:ap-southeast-2:094928090547:DevGeodesy-SiteLogReceived-1IWPAM65IAEVH"
gws_oidc_client_id_key="GwsOidcClientId"
gws_oidc_client_password_key="DevGwsOidcClientPassword"
gws_system_user_id_key="GwsSystemUser"
gws_system_user_password_key="DevGwsSystemUserPassword"
oauth2_url="https://devgeodesy-openam.geodesy.ga.gov.au/openam/oauth2"
gws_url="https://dev.geodesy.ga.gov.au"
