environment="dev"
read_only_user_arns=["arn:aws:iam::688660191997:root"]
sns_arn="arn:aws:sns:ap-southeast-2:094928090547:DevGeodesy-SiteLogReceived-DMR00D4K5T26"
gws_oidc_client_id_key="GwsOidcClientId"
gws_oidc_client_password_key="DevGwsOidcClientPassword"
gws_system_user_id_key="GwsSystemUser"
gws_system_user_password_key="DevGwsSystemUserPassword"
oauth2_url="https://devgeodesy-openam.geodesy.ga.gov.au/openam/oauth2"
gws_url="https://dev.geodesy.ga.gov.au"
ftp_sitelogs = false
sitelog_ftp_host = "system-test-ftp.dev-data.gnss.ga.gov.au"
sitelog_ftp_username = "systemTestFtpUser",
sitelog_ftp_password_key = "/gnss-data-dev-system-test-ftp/user/systemTestFtpUser/password"
parameter_store_role_arn = "arn:aws:iam::023072794443:role/parameter-store-dev-read-only"
