environment="test"
sns_arn="arn:aws:sns:ap-southeast-2:094928090547:TestGeodesy-SiteLogReceived-CHQ3QI0J97RQ"
gws_oidc_client_id_key="GwsOidcClientId"
gws_oidc_client_password_key="TestGwsOidcClientPassword"
gws_system_user_id_key="GwsSystemUser"
gws_system_user_password_key="TestGwsSystemUserPassword"
oauth2_url="https://testgeodesy-openam.geodesy.ga.gov.au/openam/oauth2"
gws_url="https://test.geodesy.ga.gov.au"
